version: 2.1
jobs:
 trial:
   docker:
    - image: circleci/ruby:2.5.3
   parallelism: 15
   steps:
     - run:
        name: install Dependencies
        command: |
          sudo su --command ""

workflows:
 version: 2.1
 build:
   jobs:
     - trial
